name: Process input data on the Backend

on:
  push:
    branches:
      - main
    paths:
      - 'gift0/cb.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency: 
      group: "webapp"
      cancel-in-progress: false

jobs:
  backend_process_file:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Get repository files
        uses: actions/checkout@v4

      - name: Remove old output files
        run: |
          if [ -f gift0/output_response ]; then
            rm gift0/output_response;
          fi;

      - name: Create input text
        run: |
          INPUT_TEXT="$(cat gift0/cb.txt | cut -d '|' -f 1)"; 
          echo "INPUT_TEXT = $INPUT_TEXT"; 
          REPO_NAME="$(cat gift0/cb.txt | cut -d '|' -f 2)"

      - name: Obtain model response
        run: |
          model_response=$(curl -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${{ secrets.API_KEY }}' -H 'Content-Type:application/json' -d '{"contents":[{"parts":[{"text":"'$INPUT_TEXT'"}]}]}');
          echo "model_response = $model_response"; 
          echo "$model_response" >> gift0/output_response;

      - name: Commit and push changes
        run: |
          repoOwner=$(echo "${{ github.repository }}" | cut -d '/' -f 1);
          repoOwnerEmail="j622amilah@gmail.com";
          
          git config --global user.email ${repoOwnerEmail};
          git config --global user.name ${repoOwner};
          git pull origin main;
          git checkout main;
          git branch --set-upstream-to origin/main;
          git merge main --ff-only;
          git add -A; 
          git diff-index --quiet HEAD || git commit -m "add files" --allow-empty;
          git push;
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install puppeteer; 

      - name: Load webpage using a non-graphical browser
        uses: actions/github-script@v6
        env:
          model_response: '$model_response'
        with:
          result-encoding: string
          script: |
            const puppeteer = require('puppeteer');
            try {
              const URL = "https://codesolutions2.github.io/quote_to_chatbot_gifts/gift0/index5.html#";
              const browser = await puppeteer.launch({headless: false});
              const page = await browser.newPage();
              
              page.on('load', () => { console.log('Page loaded successfully'); });
              
              await page.goto(URL);

              await page.evaluate(() => { document.querySelector('#notify_that_response_is_done').click(); });

              // Output text to HTML element
              await page.type('#response', 'Workflow in progress');
              
              await page.waitForSelector('#notify_that_response_is_done', {visible: true});
              
              await browser.close();
              
            } catch (error) {
              console.log('error: ', error);
            }
