name: Process input data on the Backend (file)

on:
  push:
    branches:
      - main
    paths:
      - 'src/cb0.txt'


# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency: 
      group: "webapp"
      cancel-in-progress: false

jobs:
  backend_process_file:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Get repository files
        uses: actions/checkout@v4

      - name: Remove old output files
        run: |
          if [ -f src/output_response.txt ]; then
            rm src/output_response.txt;
          fi;

      - name: Obtain input text and model response
        run: |
          # ---------------------------------------
          model_type="$(cat src/cb0.txt | cut -d '|' -f 1)"
          echo "model_type = $model_type";
          # ---------------------------------------
          model_type_KEY="$(cat src/cb0.txt | cut -d '|' -f 2)"
          echo "model_type_KEY = $model_type_KEY";
          # ---------------------------------------
          TEXT_QUOTES="$(cat src/cb0.txt | tr -s ' ' | cut -d '|' -f 3)"
          echo "TEXT_QUOTES = $TEXT_QUOTES";
          # ---------------------------------------
          INPUT_TEXT="$(cat src/cb0.txt | tr -s ' ' | cut -d '|' -f 4)"; 
          echo "INPUT_TEXT = $INPUT_TEXT";
          # ---------------------------------------
          PROMPT='$(echo "You have a personality that embodies the following text quotes - '"$TEXT_QUOTES"'. The text quotes are things that your persona would say and know. Using your persona, respond to the following question - '"$INPUT_TEXT"'")';
          echo "PROMPT = $PROMPT";
          # ---------------------------------------
          
