name: Process input data on the Backend

on:
  push:
    branches:
      - main
    paths:
      - 'gift0/cb.txt'

jobs:
  process_file:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Get repository files
        uses: actions/checkout@v4

      - name: Create input text
        run: INPUT_TEXT="$(cat gift0/cb.txt | cut -d '|' -f 1)"; echo "INPUT_TEXT = $INPUT_TEXT"; REPOA_NAME="$(cat gift0/cb.txt | cut -d '|' -f 2)"

